# Generated by Django 4.2.3 on 2023-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark Theme')], default='light', max_length=10),
        ),
    ]
