# Generated by Django 4.2.3 on 2023-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_settings_language_alter_settings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='base/product_images/'),
        ),
    ]
